### ISSUE TITLE
Start of the basic database collections.

### ISSUE THREAD

**Issue by Scott-Yuk** [warrior-ride-buddies/warrior-ride-buddies#16]
Start on the basic database collections to start adding functionality to our app. 
Issue-16

- [ ] Username
- [ ] User password
- [ ] Email
- [ ] Address
- [ ] Car information (license plate #, model, color)
- [ ] etc...

**Comment by Kobeyarai808** [comment]
Please see issue #15 for progress made there. I have basically finished the user portion of the database collection.
