### ISSUE TITLE
Change Github Organization Logo

### ISSUE THREAD

**Issue by Kobeyarai808** [warrior-ride-buddies/warrior-ride-buddies#24]
Change the Logo of the Warrior Ride Buddies Organization to be the app logo.

**Comment by alyssia-chen** [comment]
<img width="1066" alt="Screen Shot 2022-04-14 at 7 54 17 PM" src="https://user-images.githubusercontent.com/84742988/163527548-d4231653-62d0-466b-96d8-ecb94089cf89.png">

Background is transparent
