### ISSUE TITLE
Add user profile image url to user collections

### ISSUE THREAD

**Issue by William-Liang808** [warrior-ride-buddies/warrior-ride-buddies#45]
Do work on issue-45 branch

- [x] Store user image URL in database/user collections
- [ ] Add modal/form to popup after hovering over profile image in Edit Profile modal

**Comment by alyssia-chen** [comment]
Got code to upload images but wasn't able to test capturing the value (link to the uploaded image) because editing profile form is WIP

**Comment by alyssia-chen** [comment]
<img width="1440" alt="Screen Shot 2022-04-27 at 11 47 37 AM" src="https://user-images.githubusercontent.com/84742988/165636787-7cc1891d-3eb8-466b-9360-8f34c114315a.png">
