### ISSUE TITLE
Add clear buttons to filter

### ISSUE THREAD

**Issue by William-Liang808** [warrior-ride-buddies/warrior-ride-buddies#53]
Add clear buttons to filter to each individual filter inputs as well as a clear all button at the bottom of the filter.

Create branch for issue-53

**Comment by alyssia-chen** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/84742988/165003457-3438fc8d-ba37-4378-b81b-f231664d90cb.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/84742988/165003474-13024939-7617-46a8-b5a9-5ee6d4469154.png">
