### ISSUE TITLE
Create a profile page

### ISSUE THREAD

**Issue by alyssia-chen** [warrior-ride-buddies/warrior-ride-buddies#6]
Please do work for this task in a branch named issue-06.

After you click on a pin (with a digital headshot), this page shows more info about this person and allows you to contact them about riding or driving through the in-app chat.

- [ ] Contact information
- [ ] Arrival time
- [ ] Location
- [ ] Button to start an in-app chat with the person you clicked on
- [ ] Picture
- [ ] Car make/model if applicable

**Comment by Kobeyarai808** [comment]
Formatted the two-column layout
